version: '1.1'
services:
  linuxhealth:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    # volumes:
    #   - /volumes:/linux-performance